# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, default=2500.0, max_digits=1000)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Paid', 'Soldé'), ('Late', 'Retard'), ('Pending', 'En Attente')], max_length=100)),
                ('billing_order', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order')),
            ],
        ),
    ]
