# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180420_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_billings', to='order.Order'),
        ),
    ]
