# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20180424_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['pk']},
        ),
    ]
