# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180425_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
