# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180424_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
