# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerprofile_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.CharField(choices=[('abidjan', 'Abidjan'), ('bouake', 'Bouaké'), ('daloula', 'Daloula')], default='abidjan', max_length=255),
        ),
    ]
