# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180425_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='structure_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
