# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customerprofile_structure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='groupzone',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Group'),
        ),
    ]
