# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180504_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='structure_name',
        ),
    ]
