# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=60000.0, max_digits=1000)),
                ('advance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=1000)),
                ('reste', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(choices=[('created', 'Creer'), ('paid', 'Paye'), ('shipped', 'Livre'), ('refunded', '')], max_length=100)),
                ('shipped', models.BooleanField(default=False)),
                ('shipped_at', models.DateField(default=None, null=True)),
                ('month_to_pay', models.IntegerField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomerProfile')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
    ]
