# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_shipped_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Crée'), ('paid', 'Payé'), ('shipped', 'Livré'), ('refunded', '')], max_length=100),
        ),
    ]
