# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180420_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
