# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180420_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
