# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180420_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reste',
            new_name='rest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_shipped_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 20, 9, 20, 15, 451151), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_shipped_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Crée'), ('paid', 'Payé'), ('shipped', 'Livré'), ('refunded', 'Recuperer')], default='created', max_length=100),
        ),
    ]
