# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180420_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 20, 9, 25, 36, 850947), null=True),
        ),
    ]
