# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20180420_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 20, 10, 10, 10, 716980), null=True),
        ),
    ]
