# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20180421_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='mount',
            field=models.CharField(choices=[('rayban classic', 'RayBan Classic'), ('rayban homme', 'RayBan Homme')], default='rayban classic', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerProfile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 4, 23, 55, 374393), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Crée'), ('paid', 'Payé'), ('shipped', 'Livré'), ('refunded', 'Recuperé')], default='created', max_length=100),
        ),
    ]
