# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20180424_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 10, 9, 18, 621328), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Crée'), ('paid', 'Soldé'), ('shipped', 'Livré'), ('refunded', 'Recuperé')], default='created', max_length=100),
        ),
    ]
