# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20180424_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_month_complete',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 10, 19, 7, 495429), null=True),
        ),
    ]
