# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20180424_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 16, 50, 2, 442022), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_shipped_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
