# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180425_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 25, 10, 33, 6, 190083), null=True),
        ),
    ]
