# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180421_1236'),
        ('order', '0028_auto_20180425_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 25, 12, 35, 28, 536246), null=True),
        ),
    ]
