# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20180425_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 3, 10, 40, 57, 392281), null=True),
        ),
    ]
