# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20180504_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 4, 11, 55, 53, 462723), null=True),
        ),
    ]
