# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20180504_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_profile',
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 7, 13, 25, 38, 163251), null=True),
        ),
    ]
