# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20180507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 7, 13, 43, 54, 457730), null=True),
        ),
    ]
