# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20180507_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mount',
            field=models.CharField(blank=True, choices=[('rayban classic', 'RayBan Classic'), ('rayban', 'RayBan'), ('chat', 'Chat')], default='rayban classic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 7, 15, 10, 4, 788080), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Type'),
        ),
    ]
