# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20180507_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Non Livré'), ('paid', 'Soldé'), ('shipped', 'Livré'), ('refunded', 'Recuperé')], default='created', max_length=100),
        ),
    ]
