# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20180507_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_count',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
