# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180421_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addition',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
