# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180421_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cylindre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sphere',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
